namePrefix: production-
commonLabels:
  variant: production

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/ingress.yaml

# patchesStrategicMerge:
# - deployment.yaml

# vars:
# - name: IMAGE_NAME
#   objref:
#     kind: String
#     name: my-secret
#     value: 836835706379.dkr.ecr.eu-west-3.amazonaws.com/oc/occoursesexplorer
#     apiVersion: v1
# - name: IMAGE_VERSION
#   objref:
#     kind: Secret
#     name: my-secret
#     value: latest
#     apiVersion: v1
# - name: MY_SERVICE_NAME
#   objref:
#     kind: Service
#     name: my-service
#     apiVersion: v1
#   fieldref:
#     fieldpath: metadata.name
